version: '3.8'

services:
  discord-bot:
    build: .
    container_name: gge-assistant
    restart: unless-stopped
    ports:
      - "60001:5011"
    env_file:
      - .env
    environment:
      - GGE_SERVER=${GGE_SERVER:-E4K_FR1}
      - DATA_PATH=/app/data
      - TZ=Europe/Paris
    user: "1001:1001"
    volumes:
      - .:/app