services:
  discord-bot:
    image: ghcr.io/nathael-aa/gge-assistant-bot:latest
    container_name: gge-assistant
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "60011:5011"
    env_file:
      - .env
    environment:
      - GGE_SERVER=${GGE_SERVER:-E4K_FR1}
      - DATA_PATH=/app/data
      - TZ=Europe/Paris
    user: "1001:1001"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs